<a href="https://colab.research.google.com/github/Pushpalatha-H/NLP/blob/main/3_nlp_regex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Regex in nlp is matching pattern in text and retreviewing key information out of it. pattern matching for emails mobile numbers, etc

In [1]:
import re              #regular expression allows to do pattern matching.

in regex101 website for singledigit \d, \d\d for 2, for continous 10 digit \d{10}

In [2]:
chat1 = 'codebasics: you ask lot of questions 1234567891, abc@xyz.com'
chat2 = 'codebasics: here it is: (123)-567-8912, abc_82@xyz.com'
chat3 = 'codebasics: yes, phone: 1235678912 email: abc@xyz.com'

In [3]:
pattern ='\d{10}'       #to find continuous 0 digit
matches = re.findall(pattern, chat1)
matches

['1234567891']

it will show even it has 2 set of numbers in same sentence

In [4]:
chat4 = 'codebasics: here are numbers: 1234567249, 1345678928'
pattern = '\d{10}'
matches = re.findall(pattern, chat4)
matches

['1234567249', '1345678928']

to match chat2 it has (123)-567-8912 in regex we use \(\d{3}\)-\d{3}-\d{4} , to nullify the braces we use \ along with that , if we use only braces() it will select all the thing. But to select only that (123) num we use \(\)

In [5]:
pattern = '\(\d{3}\)-\d{3}-\d{4}'       # add \near braces to get only 3
matches = re.findall(pattern, chat2)
matches

['(123)-567-8912']

To select both the numbers (123)-567-8912 format and 1234567891  we should use or in between that

In [6]:
pattern = '/\d{10}|\(\d{3}\)-\d{3}-\d{4}'    # 1st apttern for continous 10 digit and second is for other format

matches = re.findall(pattern, chat2)
matches

['(123)-567-8912']

To match the email that is in the format xxx@xxx.com


In [7]:
#[a-z] for single character , so add * to select all from [a-z]
#[a-z0-9A-Z_]*@[a-z0-9A-Z_]*\.[a-z]   # to select small alphabet, capital, numbers and underscore, * is to select all

pattern = '[a-z0-9A-Z_]*@[a-z0-9A-Z_]*\.[a-z]*'

matches = re.findall(pattern, chat2)
matches

['abc_82@xyz.com']

In [8]:
#or
pattern = '[a-z0-9A-Z_]*@[a-z0-9A-Z_]*\.[a-z]*'

matches = re.findall(pattern, chat3)
emails = matches[0]
emails

'abc@xyz.com'

To import order number from the chats

In [9]:
chat1='codebasics: Hello, I am having an issue with my order # 412889922'
chat2='codebasics: I have a problem with my order number 412889912'
chat3='codebasics: My order 412889913 is having an issue, I was charged 300$ when online it says 280$'

In [10]:
# first we should find order, so type order
# second we should get all the elements which are not in digits. i.e, anything b/w word order and numbers present
# so [^\d] this is choose anything except digits , it will select single digit, to select all add *, so, [^\d]*
# third choose all the digits \d* , we only need order number so add braces for that (\d*)
# order[^\d](\d*)

In [11]:

import re

pattern = 'order[^\d]*(\d*)'
matches = re.findall(pattern, chat3)
matches

['412889913']

Extracting information from the text

In [12]:
text='''
Born	Elon Reeve Musk
June 28, 1971 (age 50)
Pretoria, Transvaal, South Africa
Citizenship
South Africa (1971–present)
Canada (1971–present)
United States (2002–present)
Education	University of Pennsylvania (BS, BA)
Title
Founder, CEO and Chief Engineer of SpaceX
CEO and product architect of Tesla, Inc.
Founder of The Boring Company and X.com (now part of PayPal)
Co-founder of Neuralink, OpenAI, and Zip2
Spouse(s)
Justine Wilson
​
​(m. 2000; div. 2008)​
Talulah Riley
​
​(m. 2010; div. 2012)​
​
​(m. 2013; div. 2016)
'''

### to get age

In [13]:
# to get age
pattern = 'age (\d+)'    # + means one or more digit, * means zero or more digit, ( ) to get only age as o/p

matches = re.findall(pattern, text)
matches

['50']

In [14]:
# to get name which ispresent after Born
#Born(.*)\n  ,  # . means any character, * means zero or more character, () to get only name, \n means end of the line

### To get name from text

In [15]:
# to get name from text which is after Born
pattern = 'Born(.*)\n'

matches = re.findall(pattern, text)
matches[0].strip()  # strip to remove the white spaces \t

'Elon Reeve Musk'

In [16]:
# get date of birth which is below the Born line
# copy paste the previous one 'Born.*\n(.*)\(age)'    # '.' means anything after born line, '*' means everything after born line,
                                                      # '\(age)'  means before age or except age

### To get date of birth

In [17]:
pattern = 'Born.*\n(.*)\(age'

matches = re.findall(pattern, text)
matches

['June 28, 1971 ']

In [18]:
# to get birth place which is below the age line
# age.*/n(.*)  # age after that , '.'anything, '*' everything, '/n' end of the line,
# after the age line '.' anything '*' everything , () to get only that thing

### To get born place

In [19]:
#Born place
pattern = 'age.*\n(.*)'

matches = re.findall(pattern, text)
matches

['Pretoria, Transvaal, South Africa']

In [20]:
def get_pattern_match(pattern, text):
  matches = re.findall(pattern, text)
  if matches:
    return matches[0]

In [21]:
get_pattern_match('age.*\n(.*)', text)

'Pretoria, Transvaal, South Africa'

In [22]:
def extract_personal_information(text):
  age = get_pattern_match('age (\d+)', text)
  full_name = get_pattern_match('Born(.*)\n', text)
  dob = get_pattern_match('Born.*\n(.*)\(age', text)
  birth_place = get_pattern_match('age.*\n(.*)', text)
  return {
      'age' : str(age),
      'name' : full_name.strip(),
      'dob' : dob.strip(),
      'birth_place' : birth_place.strip()
  }

In [23]:
extract_personal_information(text)

{'age': '50',
 'name': 'Elon Reeve Musk',
 'dob': 'June 28, 1971',
 'birth_place': 'Pretoria, Transvaal, South Africa'}

In [24]:
def get_pattern_match(pattern, text):
  matches = re.findall(pattern, text)
  if matches:
    return matches[0]

In [25]:
get_pattern_match('age.*\n(.*)', text)

'Pretoria, Transvaal, South Africa'

1. Extract all twitter handles from following text. Twitter handle is the text that appears after https://twitter.com/ and is a single word. Also it contains only alpha numeric characters i.e. A-Z a-z , o to 9 and underscore _

In [26]:
text = '''
Follow our leader Elon musk on twitter here: https://twitter.com/elonmusk, more information
on Tesla's products can be found at https://www.tesla.com/. Also here are leading influencers
for tesla related news,
https://twitter.com/teslarati
https://twitter.com/dummy_tesla
https://twitter.com/dummy_2_tesla
'''
pattern = 'https://twitter\.com/([a-zA-Z0-9_]+)' # todo: type your regex here

re.findall(pattern, text)

['elonmusk', 'teslarati', 'dummy_tesla', 'dummy_2_tesla']

2. Extract Concentration Risk Types. It will be a text that appears after "Concentration Risk:", In below example, your regex should extract these two strings

(1) Credit Risk

(2) Supply Rish

In [27]:
text = '''
Concentration of Risk: Credit Risk
Financial instruments that potentially subject us to a concentration of credit risk consist of cash, cash equivalents, marketable securities,
restricted cash, accounts receivable, convertible note hedges, and interest rate swaps. Our cash balances are primarily invested in money market funds
or on deposit at high credit quality financial institutions in the U.S. These deposits are typically in excess of insured limits. As of September 30, 2021
and December 31, 2020, no entity represented 10% or more of our total accounts receivable balance. The risk of concentration for our convertible note
hedges and interest rate swaps is mitigated by transacting with several highly-rated multinational banks.
Concentration of Risk: Supply Risk
We are dependent on our suppliers, including single source suppliers, and the inability of these suppliers to deliver necessary components of our
products in a timely manner at prices, quality levels and volumes acceptable to us, or our inability to efficiently manage these components from these
suppliers, could have a material adverse effect on our business, prospects, financial condition and operating results.
'''
pattern = 'Concentration of Risk:(.*)\n' # todo: type your regex here

re.findall(pattern, text)

[' Credit Risk', ' Supply Risk']

In [28]:
text = '''
Tesla's gross cost of operating lease vehicles in FY2021 Q1 was $4.85 billion.
BMW's gross cost of operating vehicles in FY2021 S1 was $8 billion.
'''

pattern = 'FY(\d{4} [a-zA-Z0-9_]+)'
matches = re.findall(pattern, text)
matches

['2021 Q1', '2021 S1']

[4. Nlp]. There are three techniques to solve nlp problem
1. Rule & Heuristics
2. Machine Learning
3. Deep Learning

NLP Technique
1. To classify the complaint as high, medium and low

[text]-----> [TF-IDF Vectorizer]---->[0.36, 0.67, 0.222, 0,0,0.56,...]--->[Naive Bayes Classifier]---->[High, Medium, low]   , TF-IDF Vectorizer will convert text into numbers

2. if we have images of medical prescripton and patients record stored in cloud, here ML come into use

[image stored in cloud]----->[Apply OCR(Google Tesseract OCR)]---->[Text]--->[Doc2Vec]--->[0.36,0.67,0.299,0,0,0.56...]--->[Logistic Regression Classification]-----[Prescription, Patient Record]

3. Hate speech detection by Facebook

They deveoped a algorithm which predicted hate speech detection, now then can automatically delete hate speech

Even linkedin has some algorithm to detect the profile is fake or not

[2]. Text Similarity

i. Matching resume with similar key words like using Hugging Face we can get the similarity score,

ii. Resume Screener matching particular resume with job discriptions



job descrip[skills:Requried]--->[Sentence Encoder]--->[45,12,45,..]---------------->
                                                                             [Cosine Similarity]

Resume[Exploratory data analysis using pandas....]--->[Sentence Encoder]--->[41,10,7....]---------->     [Cosine similarity] 65%

[3].Information Extraction

ex: Google keyword extraction

[4]. Information Retrival

ex:
(i). Google search like salon near me it will show the relevant results according to my location and all

(ii). TFIDF Score and BERT for information Retrival

(iii). ChatBots
   i. FAQ Bot which has fixed number of answers
   ii. Flow-Based Bot i.e, connection b/w previous chat and recent chat
   iii. Open-Ended Bot i.e, like chit chatting with friend like general conversation more like

  (iv). Machine Translation

  ex: Google translator

(v). Language Modeling
ex: sentance auto completing by gmail
    i. Statistical Model
    ii. Neural Model

(V). Text Summarization
ex: Summarizing the whole article to a single sentence


(Vi). Topic Modeling

We can use topic modelling to retrive the extract toppics out of it.

(vii). Voice Assistants

##NLP Pipe Line ##

step1 : **Data Acquisition** : To get necessary data required to solve nlp problem

i. By using the data present in company from past years

ii. Use a public dataset such as
  i. Google has search engine for datasets

  ii. us consultancies has lot of economic data

  iii. Use webscrapping to scrape the data from internet
  
  iv. Product inervention, data agumentation, etc..

step 2: **Text Extraction & Cleanup**

i. Discard irrelevant information and creating simple version of your text data

ii. spelling correction + Remove \n\n

iii. Sentence Segmentation or Sentence tokenization (splitting the sentence)

iv. word tokenization(splitting words)

v. Stemming : loves -> love, eating -> eat, adjustable -> adjust

vi. Lemmatization: mapping the word to its base word (ate -> eat, was -> (to)be, better -> good, meeting -> meeting)



First three steps in NLP Pipeline

[Data Acquisition]---->[Text Extraction & Cleanup]---->[Pre-processing]---> [Feature Engineering]
|down|

|up|

[Monitor & Update]<----------------[Deployment]<-------------[Evaluation]<---------[Model building]

we get textad o/p, should convert words to numbers coz machine learning cannot understand words.

This method of extracting words into numbers is called **Feature Engineering**

The method for converting words into numbers are [TF-IDF Vectorizer, One Hot Encoding, Word Embedding]

**Model building**: Building a model to predict the ticket whether it is high, medium or low by using [Naive Bayes Classifier, SVM, Random Forest]



##Spacy vs NLTK

When building NLP application we might end up using many libraries such as Spacy, NLTK, Gensim, pytorch, Tensorflow, Hugging Face,..

Spacy and NLTK is most widely used NLP libraries

In [29]:
!pip install nltk

In [30]:
!pip install spacy

##Spacy##

In [31]:
import spacy

In [32]:
nlp = spacy.load("en_core_web_sm")    # we are going to use english core package for this

doc = nlp("Dr. Strange loves pav bhaji of mumbai. Hulk loves chat of delhi")      # split paragraph into sentences then to words

for sentence in doc.sents:       # sentence tokenization in spacy
  print(sentence)



Dr. Strange loves pav bhaji of mumbai.
Hulk loves chat of delhi


In [33]:
for sentence in doc.sents:        # word tokenization
  for word in sentence:           # By looking at the code we can say that spacy is a object oriented programme
    print(word)

Dr.
Strange
loves
pav
bhaji
of
mumbai
.
Hulk
loves
chat
of
delhi


## nltk##

In [34]:
import nltk           #nltk

nltk.download("punkt")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [35]:
from nltk.tokenize import sent_tokenize         #nltk is a string processing library

sent_tokenize("Dr. Strange loves pav bhaji of mumbai. Hulk loves chat of delhi")      # we got 3 sentences o/p here, it is not object oriented

['Dr.', 'Strange loves pav bhaji of mumbai.', 'Hulk loves chat of delhi']

In [36]:
from nltk.tokenize import word_tokenize
word_tokenize("Dr. Strange loves pav bhaji of mumbai. Hulk loves chat of delhi")

['Dr',
 '.',
 'Strange',
 'loves',
 'pav',
 'bhaji',
 'of',
 'mumbai',
 '.',
 'Hulk',
 'loves',
 'chat',
 'of',
 'delhi']

##Spacy##                                                               
i. Spacy is Object Oriented

ii. Spacy provides most efficient NLP algorithm for a given task. Hence if you care about the end result, go with Spacy.

iii. Spacy is user friendly

iv. Spacy is perfect for app developers

v. Spacy is new library and has a very active user community

##NLTK##
i. NLTK is mainly a string processing library

ii. NLTK provides access to many algorithm. If you care about specific algo and customizations go with NLTK

iii. NLTK is also a userfriendly but less user friendly compared to Spacy

iv. NLTK is perfect for esearchers

v. NLTK is old library. User community not as active as Spacy
